Repository prgrms-web-devcourse-final-project/WEB2_3_Wooamo_FE, pull requests merged in 2025-02, with the labels that each got.

#1 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Chore

#6 [STYLE] 채팅 페이지 퍼블리싱
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/ChattingHeader.tsx
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/chatting/ChattingListItem.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/layout.tsx
Labels: 🎨 Style

#10 [STYLE] 채팅 페이지 모바일 퍼블리싱
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/ChattingHeader.tsx
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/chatting/ChattingListItem.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/header.tsx
  src/app/(with-main-header)/layout.tsx
Labels: 🎨 Style

#13 [STYLE] 게시판, 팟, 홈, 다른 유저 프로필 페이지에 반응형 적용
  .prettierrc
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/RankingCard.tsx
  src/app/(with-main-header)/boards/BoardsHeader.tsx
  src/app/(with-main-header)/boards/PostImage.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/app/(with-main-header)/boards/[id]/Comments.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/app/(with-main-header)/layout.tsx
  src/app/(with-main-header)/page.tsx
  src/app/(with-main-header)/party/ClosedParties.tsx
  src/app/(with-main-header)/party/EventParties.tsx
  src/app/(with-main-header)/party/OngoingParties.tsx
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/UpcomingParties.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/party/create/page.tsx
  src/app/(with-main-header)/party/page.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/(with-main-header)/users/[id]/page.tsx
  src/assets/css/globals.css
  src/components/common/Icon.tsx
  src/components/common/Input.tsx
  src/components/common/InputIcon.tsx
  src/components/ui/button.tsx
  src/components/ui/datePicker.tsx
Labels: 🎨 Style

#12 [STYLE] 관리자 페이지 퍼블리싱
  src/app/(with-admin-header)/admin/AdminHeader.tsx
  src/app/(with-admin-header)/admin/AdminSidebar.tsx
  src/app/(with-admin-header)/admin/PartyList.tsx
  src/app/(with-admin-header)/admin/PaymentList.tsx
  src/app/(with-admin-header)/admin/layout.tsx
  src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
  src/app/(with-admin-header)/admin/manage/event/EventItem.tsx
  src/app/(with-admin-header)/admin/manage/event/page.tsx
  src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
  src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
  src/app/(with-admin-header)/admin/manage/item/page.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationDate.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/ParticipantItem.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/page.tsx
  src/app/(with-admin-header)/admin/manage/party/page.tsx
  src/app/(with-admin-header)/admin/page.tsx
  src/components/common/Modal.tsx
Labels: 🎨 Style

#16 [STYLE] 회원가입 및 로그인 페이지 반응형 적용
  src/app/(with-auth-header)/layout.tsx
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-auth-header)/signup/page.tsx
  src/assets/css/globals.css
  src/assets/images/MobilekakaoLoginButton.png
  src/components/common/InputWithErrorMsg.tsx
Labels: 🎨 Style

#19 [STYLE] 로그인 후 메인페이지 데스크탑 퍼블리싱
  src/app/(with-main-header)/AfterLoginHome.tsx
  src/app/(with-main-header)/BeforeLoginHome.tsx
  src/app/(with-main-header)/Timer.tsx
  src/app/(with-main-header)/TimerCategory.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoList.tsx
  src/app/(with-main-header)/UserCard.tsx
  src/app/(with-main-header)/page.tsx
Labels: 🎨 Style

#22 💄 홈(로그인 후) 반응형 적용
  src/app/(with-main-header)/AfterLoginHome.tsx
  src/app/(with-main-header)/BeforeLoginHome.tsx
  src/app/(with-main-header)/Timer.tsx
  src/app/(with-main-header)/TimerCategory.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoList.tsx
  src/app/(with-main-header)/UserCard.tsx
Labels: 🎨 Style

#17 [STYLE] 알림목록 퍼블리싱 및 반응형 적용
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/components/common/Avatar.tsx
  src/components/common/Icon.tsx
  src/components/common/NotificationList.tsx
  src/types/notification.ts
Labels: 🎨 Style

#25 [CHORE] API Request + Response 타입 설정 샘플 추가
  env.d.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
Labels: ⚙ Chore

#26 [FEAT] 어드민 메인 페이지
  next.config.ts
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/app/(with-admin-header)/admin/PartyList.tsx
  src/app/(with-admin-header)/admin/PaymentList.tsx
  src/app/(with-admin-header)/admin/manage/party/page.tsx
  src/app/(with-admin-header)/admin/page.tsx
Labels: ✨Feature

#28 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Chore

#29 [FEAT] 회원가입 기능 구현
  src/api/auth/auth.ts
  src/api/auth/auth.type.ts
  src/api/common.type.ts
  src/api/user/user.type.ts
  src/app/(with-auth-header)/signup/page.tsx
  src/assets/css/globals.css
  src/hooks/useInputValidation.ts
Labels: ✨Feature

#35 Feat/login
  src/api/auth/auth.ts
  src/api/auth/auth.type.ts
  src/api/common.type.ts
  src/app/(with-auth-header)/signin/page.tsx
Labels: ✨Feature

#38 [FEAT] 로그인 - 로그인 후, 헤더가 로그인 이후 상태로 보이도록 처리
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/store/authStore.ts
Labels: ✨Feature

#39 [FEAT] 홈 페이지 기능 구현 (타이머 제외)
  src/api/timer/timer.ts
  src/api/timer/timer.type.ts
  src/api/todo/todo.ts
  src/api/todo/todo.type.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
  src/app/(with-main-header)/AfterLoginHome.tsx
  src/app/(with-main-header)/BeforeLoginHome.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoList.tsx
  src/app/(with-main-header)/UserCard.tsx
  src/app/(with-main-header)/page.tsx
  src/components/common/Character.tsx
  src/components/common/Dropdown.tsx
  src/store/todoStore.ts
Labels: ✨Feature

#41 [FEAT] 로그아웃 기능 구현
  src/app/(with-main-header)/DesktopHeader.tsx
  src/components/common/Dropdown.tsx
Labels: ✨Feature

#43 [FEAT] 관리자 페이지 이벤트 페이지
  next.config.ts
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
  src/app/(with-admin-header)/admin/manage/event/EventItem.tsx
  src/app/(with-admin-header)/admin/manage/event/page.tsx
  src/app/actions.ts
  src/components/common/Modal.tsx
  src/components/ui/popover.tsx
Labels: ✨Feature

#45 [FEAT] 어드민 페이지 팟 관리 페이지(일부 완료)
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationDate.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/ParticipantItem.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/page.tsx
Labels: ✨Feature

#44 [FEAT] 마이페이지 기능 구현 (공부 시간 제외)
  src/api/friend/friend.ts
  src/api/friend/friend.type.ts
  src/api/timer/timer.ts
  src/api/timer/timer.type.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/mypage/ProfileEditButton.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/components/common/Avatar.tsx
Labels: ✨Feature

#48 [FEAT] 어드민 페이지 아이템 관리 페이지
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/api/shop/shop.ts
  src/api/shop/shop.type.ts
  src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
  src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
  src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
  src/app/(with-admin-header)/admin/manage/item/page.tsx
Labels: ✨Feature

#49 [FEAT] 친구 페이지 기능 구현
  src/api/friend/friend.ts
  src/api/friend/friend.type.ts
  src/app/(with-main-header)/friends/FriendsItem.tsx
  src/app/(with-main-header)/friends/FriendsRequestItem.tsx
  src/app/(with-main-header)/friends/add/SearchedUserItem.tsx
  src/app/(with-main-header)/friends/add/page.tsx
  src/app/(with-main-header)/friends/page.tsx
  src/components/common/ProfileSummary.tsx
Labels: ✨Feature

#51 [FEAT] 어드민 페이지 파티 관리 페이지
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationDate.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationViewer.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/ParticipantItem.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/page.tsx
Labels: ✨Feature

#52 [FEAT] 게시판 리스트, 상세 페이지 기능 구현
  src/api/board/board.ts
  src/api/board/board.type.ts
  src/api/user/user.type.ts
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/PostImage.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/app/(with-main-header)/boards/[id]/Comments.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/components/common/Character.tsx
  src/components/common/NotificationList.tsx
Labels: ✨Feature

#55 [FEAT] 상점 페이지
  env.d.ts
  package.json
  pnpm-lock.yaml
  src/api/shop/shop.ts
  src/api/shop/shop.type.ts
  src/api/user/user.ts
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: ✨Feature

#57 [FEAT] 타이머 기능
  src/api/timer/timer.ts
  src/api/timer/timer.type.ts
  src/app/(with-main-header)/Timer.tsx
  src/app/(with-main-header)/TimerCategory.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/store/timerStore.ts
Labels: ✨Feature

#59 [FEAT] 로딩 시, 스켈레톤 UI 적용
  components.json
  src/actions/todo.ts
  src/api/board/board.type.ts
  src/api/friend/friend.ts
  src/api/friend/friend.type.ts
  src/api/timer/timer.ts
  src/api/todo/todo.ts
  src/api/user/user.ts
  src/app/(with-main-header)/Timer.tsx
  src/app/(with-main-header)/TimerItem.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoItems.tsx
  src/app/(with-main-header)/TodoList.tsx
  src/app/(with-main-header)/TodoListForm.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/app/(with-main-header)/friends/FriendAcceptDenyButton.tsx
  src/app/(with-main-header)/friends/FriendDeleteButton.tsx
  src/app/(with-main-header)/friends/FriendsItem.tsx
  src/app/(with-main-header)/friends/FriendsRequestItem.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/friends/add/FriendSearch.tsx
  src/app/(with-main-header)/friends/add/SearchedUserItem.tsx
  src/app/(with-main-header)/friends/add/SearchedUsers.tsx
  src/app/(with-main-header)/friends/add/page.tsx
  src/app/(with-main-header)/friends/page.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/mypage/ProfileEditButton.tsx
  src/app/(with-main-header)/mypage/ProfileTab.tsx
  src/app/(with-main-header)/mypage/page.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyDateChanger.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyList.tsx
  src/app/(with-main-header)/users/[id]/page.tsx
  src/assets/css/globals.css
  src/assets/css/shadcn.css
  src/components/common/Icon.tsx
  src/components/common/skeletons/BasicSkeleton.tsx
  src/components/common/skeletons/FriendItemSkeleton.tsx
  src/components/common/skeletons/PostItemSkeleton.tsx
  src/components/common/skeletons/ProfileItemSkeleton.tsx
  src/components/ui/skeleton.tsx
  src/store/todoStore.ts
  src/utils/delay.ts
Labels: ✨Feature

#61 [CHORE] CI/CD 템플릿 추가
  .github/workflows/deploy.yml
Labels: ⚙ Chore

#60 [Feat] 게시판 상세, 수정 페이지 기능구현
  src/api/board/board.ts
  src/api/board/board.type.ts
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/app/(with-main-header)/boards/[id]/Comments.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/[id]/PostDeleteButton.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
Labels: ✨Feature

#67 [FEAT] 팟 페이지
  env.d.ts
  src/api/party/party.ts
  src/api/party/party.type.ts
  src/app/(with-main-header)/party/ClosedParties.tsx
  src/app/(with-main-header)/party/ClosedPartyItem.tsx
  src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
  src/app/(with-main-header)/party/EventParties.tsx
  src/app/(with-main-header)/party/OngoingParties.tsx
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/PersonalQuest.tsx
  src/app/(with-main-header)/party/UpcomingParties.tsx
  src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/party/create/page.tsx
  src/app/(with-main-header)/party/page.tsx
  src/hooks/useDebounce.ts
Labels: ✨Feature

#71 Feat/signin signup
  env.d.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/api/admin/admin.ts
  src/api/auth/auth.ts
  src/api/board/board.ts
  src/api/cookie.ts
  src/api/fetchCustom.ts
  src/api/friend/friend.ts
  src/api/shop/shop.ts
  src/api/timer/timer.ts
  src/api/todo/todo.ts
  src/api/user/user.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-auth-header)/signup/page.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/friends/[id]/page.tsx
  src/app/(with-main-header)/page.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/assets/css/globals.css
  src/components/common/ProfileSummary.tsx
  src/store/authStore.ts
Labels: ✨Feature

#73 [FEAT] 404 페이지
  src/app/not-found.tsx
  src/assets/images/NotFoundImage.svg
Labels: ✨Feature

#78 [Feat] 알림목록 기능 구현
  package.json
  pnpm-lock.yaml
  src/api/board/board.ts
  src/api/board/board.type.ts
  src/api/notification/notification.ts
  src/api/notification/notification.type.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/components/common/NotificationList.tsx
  src/hooks/useNotification.ts
  src/types/notification.ts
Labels: ✨Feature

#79 [FEAT] 배포 서버로 전환 후 어드민 페이지 로직 수정
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/api/shop/shop.ts
  src/api/shop/shop.type.ts
  src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: ✨Feature
