Repository prgrms-web-devcourse-final-project/WEB2_3_Wooamo_FE, pull requests merged in 2025-03, with the labels that each got.

#88 [FEAT] 실서버로 개발 중 수정사항
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/api/shop/shop.ts
  src/api/shop/shop.type.ts
  src/app/(with-admin-header)/admin/PartyList.tsx
  src/app/(with-admin-header)/admin/manage/party/page.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: ✨Feature

#89 [FEAT] 토스트 컴포넌트 추가 및 적용
  next.config.ts
  package.json
  src/api/fetchCustom.ts
  src/api/party/party.ts
  src/api/party/party.type.ts
  src/app/(with-main-header)/page.tsx
  src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
  src/app/(with-main-header)/party/PersonalQuest.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/layout.tsx
  src/assets/css/globals.css
  src/assets/images/Coin.svg
  src/assets/images/PixelStarLeft.svg
  src/assets/images/PixelStarRight.svg
  src/components/common/Toast.tsx
  src/store/toastStore.ts
Labels: ✨Feature

#91 [FEAT] 전체 타입 재정리
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/api/board/board.ts
  src/api/board/board.type.ts
  src/api/common.type.ts
  src/api/friend/friend.ts
  src/api/friend/friend.type.ts
  src/api/notification/notification.ts
  src/api/notification/notification.type.ts
  src/api/party/party.ts
  src/api/party/party.type.ts
  src/api/shop/shop.ts
  src/api/shop/shop.type.ts
  src/api/timer/timer.ts
  src/api/timer/timer.type.ts
  src/api/todo/todo.ts
  src/api/todo/todo.type.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
Labels: ✨Feature

#94 [FEAT] 친구 페이지 실서버 구현 (채팅 제외)
  src/api/common.type.ts
  src/api/fetchCustom.ts
  src/api/friend/friend.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/friends/add/SearchedUsers.tsx
  src/app/(with-main-header)/friends/add/page.tsx
  src/app/(with-main-header)/friends/page.tsx
  src/app/(with-main-header)/header.tsx
  src/app/(with-main-header)/layout.tsx
  src/hooks/useIsMobile.ts
Labels: ✨Feature

#95 [FEAT] 상점 페이지 실서버 구현
  src/api/party/party.ts
  src/api/shop/shop.ts
  src/api/timer/timer.ts
  src/app/(with-main-header)/TimerList.tsx
  src/app/(with-main-header)/party/OngoingParties.tsx
  src/app/(with-main-header)/party/UpcomingParties.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: ✨Feature

#96 [Feat]보드 검색기능 구현 중
  src/api/board/board.ts
  src/app/(with-main-header)/boards/BoardSearch.tsx
  src/app/(with-main-header)/boards/BoardsHeader.tsx
  src/app/(with-main-header)/boards/create/page.tsx
Labels: ✨Feature

#98 ✨ [FEAT] 실서버로 게시글 작성, 수정, 삭제, 댓글 작성, 삭제 구현
  src/api/board/board.ts
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
Labels: ✨Feature

#99 [FEAT & BUG] 타이머 기능 실서버 구현 및 버그 수정
  src/app/(with-main-header)/TimerItem.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/store/timerStore.ts
Labels: 🐞 Bug, ✨Feature

#103 [FEAT] 유저 관련 기능 실서버로 구현
  src/api/fetchCustom.ts
  src/api/friend/friend.ts
  src/api/timer/timer.ts
  src/api/todo/todo.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
  src/app/(with-auth-header)/signup/page.tsx
  src/app/(with-main-header)/AfterLoginHome.tsx
  src/app/(with-main-header)/BeforeLoginHome.tsx
  src/app/(with-main-header)/ButtonExample.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/RankingCard.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoItems.tsx
  src/app/(with-main-header)/TodoListForm.tsx
  src/app/(with-main-header)/friends/FriendsRequestItem.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/mypage/ProfileTab.tsx
  src/app/(with-main-header)/page.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/app/(with-main-header)/users/[id]/RequestFriendButton.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyDateChanger.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyList.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/(with-main-header)/users/[id]/page.tsx
  src/assets/css/globals.css
  src/components/common/Avatar.tsx
  src/components/common/Character.tsx
  src/components/common/InputWithErrorMsg.tsx
  src/middleware.ts
Labels: ✨Feature

#104 [FEAT] 팟 페이지, 어드민 페이지 실서버 구현
  src/api/admin/admin.ts
  src/api/party/party.ts
  src/api/party/party.type.ts
  src/api/user/user.ts
  src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
  src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
  src/app/(with-admin-header)/admin/manage/item/page.tsx
  src/app/(with-main-header)/BeforeLoginHome.tsx
  src/app/(with-main-header)/party/ClosedParties.tsx
  src/app/(with-main-header)/party/EventParties.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/party/page.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/components/common/ProfileSummary.tsx
Labels: ✨Feature

#106 [Feat]게시판 검색기능 구현 및 이미지 크게보기
  src/api/board/board.ts
  src/app/(with-main-header)/boards/BoardSearch.tsx
  src/app/(with-main-header)/boards/PostImage.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/components/common/Character.tsx
Labels: ✨Feature

#109 [Feat] 알림 목록 실서버 구현
  src/api/notification/notification.ts
  src/api/notification/notification.type.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/components/common/NotificationList.tsx
  src/hooks/useNotification.ts
Labels: ✨Feature

#111 Feat/before login home
  package.json
  pnpm-lock.yaml
  src/api/auth/auth.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/UserCard.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/layout.tsx
  src/components/ui/tooltip.tsx
Labels: ✨Feature

#112 [FIX] 로그인
  src/api/auth/auth.ts
  src/api/notification/notification.ts
Labels: 🐞 Bug

#113 [FEAT] 관리자 로그인 구현 및 기타 버그 수정
  src/api/auth/auth.ts
  src/app/(with-auth-header)/signin/page.tsx
Labels: ✨Feature

#116 🐛 로그인 - 401 에러 버그 수정
  src/api/auth/auth.ts
  src/api/fetchCustom.ts
  src/middleware.ts
Labels: 🐞 Bug

#117 [FEAT] 팟 페이지, 어드민 페이지 실서버 구현
  src/api/admin/admin.ts
  src/api/admin/admin.type.ts
  src/api/party/party.type.ts
  src/app/(with-admin-header)/admin/AdminHeader.tsx
  src/app/(with-admin-header)/admin/LogoutButton.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/Certification.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationDate.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/CertificationViewer.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/ParticipantItem.tsx
  src/app/(with-admin-header)/admin/manage/party/[id]/page.tsx
  src/app/(with-main-header)/party/ClosedParties.tsx
  src/app/(with-main-header)/party/ClosedPartyItem.tsx
  src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
  src/app/(with-main-header)/party/OngoingParties.tsx
  src/app/(with-main-header)/party/PersonalQuest.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: ✨Feature

#121 [FEAT] localhost에 https 적용
  .gitignore
  package.json
  src/api/auth/auth.ts
  src/api/fetchCustom.ts
  src/api/user/user.type.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
Labels: 🐞 Bug

#122 [FIX] 상점 페이지 버그 수정
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: 🐞 Bug

#124 [FIX] 팟 페이지 예외 처리 및 버그 수정(일부 완료)
  src/api/party/party.ts
  src/app/(with-main-header)/party/EventParties.tsx
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/PersonalQuest.tsx
  src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/party/page.tsx
Labels: 🐞 Bug

#125 [Fix] 게시판 페이지 버그 수정
  src/app/(with-main-header)/boards/BoardsHeader.tsx
  src/app/(with-main-header)/boards/PostImage.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/page.tsx
Labels: 🐞 Bug

#128 [Fix] 유틸함수 분리와 댓글 시간 확인
  src/app/(with-main-header)/boards/BoardsHeader.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Comment.tsx
  src/app/(with-main-header)/boards/[id]/Comments.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/utils/renderContextWithLineBreaks.tsx
Labels: 🐞 Bug

#130 [FEAT] 친구 채팅 기능 및 파티 채팅 기능 구현
  env.d.ts
  package.json
  pnpm-lock.yaml
  src/api/chatting/chatting.ts
  src/api/chatting/chatting.type.ts
  src/app/(with-auth-header)/layout.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/chatting/ChattingListItem.tsx
  src/app/(with-main-header)/chatting/create/FriendList.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/friend/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/friends/add/SearchedUserItem.tsx
  src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/store/socketStore.ts
Labels: ✨Feature

#129 [FIX] 타이머 자동저장 오류 수정
  src/app/(with-main-header)/TimerItem.tsx
  src/store/timerStore.ts
Labels: 🐞 Bug

#132 [FIX] 머지 충돌 해결
  src/api/auth/auth.ts
Labels: 🐞 Bug

#136 [FEAT] 팟 채팅 접속 시, 해당 팟에 대한 정보 조회
  package.json
  src/api/chatting/chatting.type.ts
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
Labels: ✨Feature

#137 [FEAT] revalidateTag 수정
  src/api/party/party.ts
  src/api/shop/shop.ts
  src/api/timer/timer.ts
  src/api/user/user.ts
  src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
  src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
  src/app/(with-main-header)/TimerCategory.tsx
  src/app/(with-main-header)/TimerItem.tsx
  src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/PersonalQuest.tsx
  src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
Labels: ✨Feature

#139 [FIX] 팟 검색 스켈레톤 적용 및 토스 결제 에러 핸들링
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/all/PartyItems.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
Labels: 🐞 Bug

#141 [FIX] 홈, 마이페이지, 로그인, 친구, 유저 프로필 페이지 버그 수정
  src/api/auth/auth.ts
  src/api/friend/friend.ts
  src/api/user/user.ts
  src/api/user/user.type.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/RankingCard.tsx
  src/app/(with-main-header)/TimerList.tsx
  src/app/(with-main-header)/TodoItem.tsx
  src/app/(with-main-header)/TodoItems.tsx
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
  src/app/(with-main-header)/friends/FriendsItem.tsx
  src/app/(with-main-header)/friends/[id]/page.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/friends/page.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
  src/app/(with-main-header)/users/[id]/RequestFriendButton.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/actions.ts
Labels: 🐞 Bug

#143 🐛 Cookie로 인해, 빌드 시 대부분의 페이지가 dynamic 페이지가 되는 버그 일부 수정
  src/api/auth/auth.ts
  src/api/chatting/chatting.type.ts
  src/api/user/user.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/header.tsx
  src/app/(with-main-header)/layout.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/mypage/ProfileEditButton.tsx
  src/app/(with-main-header)/page.tsx
  src/middleware.ts
  src/store/authStore.ts
  src/store/userStore.ts
Labels: 🐞 Bug

#145 [FIX] 채팅 무한 스크롤 구현 및 로딩 스피너 추가 + 기타 버그 수정
  src/api/auth/auth.ts
  src/api/chatting/chatting.ts
  src/api/chatting/chatting.type.ts
  src/api/timer/timer.ts
  src/api/user/user.ts
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingListItem.tsx
  src/app/(with-main-header)/chatting/LoadingSpinner.tsx
  src/app/(with-main-header)/chatting/friend/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/layout.tsx
  src/app/(with-main-header)/mypage/ProfileTab.tsx
  src/app/(with-main-header)/users/[id]/RequestFriendButton.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyDateChanger.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyList.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/(with-main-header)/users/[id]/page.tsx
  src/components/common/skeletons/FriendItemSkeleton.tsx
  src/hooks/useInfiniteChatting.ts
  src/middleware.ts
Labels: 🐞 Bug, ✨Feature

#147 [FEAT] 게시판, 팟 페이지 목록 페이지네이션 추가
  src/api/auth/auth.ts
  src/api/board/board.ts
  src/app/(with-main-header)/boards/BoardSearch.tsx
  src/app/(with-main-header)/boards/PostItems.tsx
  src/app/(with-main-header)/boards/page.tsx
  src/app/(with-main-header)/party/PartyItem.tsx
  src/app/(with-main-header)/party/all/Pagination.tsx
  src/app/(with-main-header)/party/all/PartyItems.tsx
  src/app/(with-main-header)/party/all/PartySearch.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/party/create/page.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
Labels: ✨Feature

#151 [Fix] board-production server 버그 수정
  src/api/board/board.ts
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/Comments.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/hooks/useSSE.ts
Labels: 🐞 Bug

#153 [FIX] 버그 수정
  src/api/party/party.ts
  src/api/user/user.ts
  src/app/(with-admin-header)/admin/AdminHeader.tsx
  src/app/(with-main-header)/party/EventParties.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/ShopCostumeItem.tsx
  src/app/(with-main-header)/shop/page.tsx
  src/components/common/Input.tsx
Labels: 🐞 Bug, ✨Feature

#157 [FIX] 채팅 버그 수정 및 옷장 레이아웃 수정
  env.d.ts
  src/api/chatting/chatting.ts
  src/api/friend/friend.ts
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/friends/[id]/page.tsx
  src/app/(with-main-header)/friends/page.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/mypage/page.tsx
  src/app/api/kakaoLogin/route.ts
  src/hooks/useInfiniteChatting.ts
  src/middleware.ts
Labels: 🐞 Bug

#156 [Fix] 알림 목록 실서버 버그 수정
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/PostItem.tsx
  src/components/common/NotificationList.tsx
  src/hooks/useNewNotification.ts
Labels: 🐞 Bug

#161 [FIX] QA 오류 수정
  src/api/shop/shop.ts
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/party/create/page.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/page.tsx
  src/app/favicon.ico
  src/consts/costumes.ts
Labels: 🐞 Bug

#163 [FIX] 채팅 및 마이페이지 등 최종 QA 버그 수정
  src/api/auth/auth.ts
  src/api/friend/friend.ts
  src/api/user/user.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/mypage/ProfileEditButton.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/(with-main-header)/users/[id]/RequestFriendButton.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/api/kakaoLogin/route.ts
  src/hooks/useInfiniteChatting.ts
  src/store/socketStore.ts
  src/store/userStore.ts
Labels: 🐞 Bug

#164 [FIX] 아이템 목록 페이지네이션 삭제 후 응답 타입 수정
  src/api/shop/shop.ts
  src/app/(with-admin-header)/admin/manage/item/page.tsx
  src/app/(with-main-header)/shop/page.tsx
Labels: 🐞 Bug

#165 Fix/게시글 목록 버그 수정
  src/api/board/board.ts
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
Labels: 🐞 Bug

#166 [FIX] 채팅 - 1대 1 채팅에서 실시간 읽음처리가 안되는 버그 수정
  src/api/chatting/chatting.type.ts
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/friend/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/components/common/WebSocketClient.ts
  src/hooks/useInfiniteChatting.ts
  src/store/socketStore.ts
Labels: 🐞 Bug

#167 메인으로 배포
  src/api/auth/auth.ts
  src/api/board/board.ts
  src/api/chatting/chatting.type.ts
  src/api/friend/friend.ts
  src/api/shop/shop.ts
  src/api/user/user.ts
  src/app/(with-admin-header)/admin/manage/item/page.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/[id]/update/page.tsx
  src/app/(with-main-header)/boards/create/page.tsx
  src/app/(with-main-header)/chatting/ChattingInput.tsx
  src/app/(with-main-header)/chatting/ChattingItem.tsx
  src/app/(with-main-header)/chatting/create/page.tsx
  src/app/(with-main-header)/chatting/friend/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/friend/[id]/page.tsx
  src/app/(with-main-header)/chatting/page.tsx
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/party/[id]/page.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/mypage/ProfileEditButton.tsx
  src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
  src/app/(with-main-header)/party/[id]/page.tsx
  src/app/(with-main-header)/party/create/CreatePartyButton.tsx
  src/app/(with-main-header)/party/create/page.tsx
  src/app/(with-main-header)/shop/ChargeButton.tsx
  src/app/(with-main-header)/shop/RandomGatchaButton.tsx
  src/app/(with-main-header)/shop/page.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/(with-main-header)/users/[id]/RequestFriendButton.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/app/api/kakaoLogin/route.ts
  src/app/favicon.ico
  src/components/common/WebSocketClient.ts
  src/consts/costumes.ts
  src/hooks/useInfiniteChatting.ts
  src/store/socketStore.ts
  src/store/userStore.ts
Labels: ✨Feature

#177 [Fix] 게시판/알림-최종 ui 수정
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/PostImage.tsx
Labels: 🐞 Bug, 🎨 Style

#178 [FIX] 팟 상세페이지 줄 바꿈 처리
  src/app/(with-main-header)/party/[id]/page.tsx
Labels: 🐞 Bug

#180 [FIX] 자동로그인 수정 및 버그 수정
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
Labels: 🐞 Bug

#183 [FEAT] 로그인 및 회원가입 성공 토스트 추가 + 기타 버그 수정
  src/api/auth/auth.ts
  src/api/auth/auth.type.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-auth-header)/signup/page.tsx
  src/app/(with-main-header)/RankingCard.tsx
  src/app/(with-main-header)/UserCard.tsx
  src/app/(with-main-header)/chatting/ChattingListItem.tsx
  src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
  src/app/(with-main-header)/mypage/MyProfile.tsx
  src/app/(with-main-header)/users/[id]/Jandy.tsx
  src/app/(with-main-header)/users/[id]/UserProfile.tsx
  src/components/common/NotificationList.tsx
Labels: ✨Feature

#190 [REFACTOR] 각종 버그 수정 및 최적화 진행
  src/api/admin/admin.ts
  src/api/auth/auth.ts
  src/api/board/board.ts
  src/api/fetchCustom.ts
  src/api/friend/friend.ts
  src/api/party/party.ts
  src/api/shop/shop.ts
  src/api/timer/timer.ts
  src/api/user/user.ts
  src/app/(with-auth-header)/signin/page.tsx
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/TimerCategory.tsx
  src/app/(with-main-header)/boards/[id]/Post.tsx
  src/app/(with-main-header)/boards/[id]/page.tsx
  src/app/(with-main-header)/layout.tsx
  src/app/(with-main-header)/party/all/page.tsx
  src/app/(with-main-header)/users/[id]/JandyDescription.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
  src/app/api/kakaoLogin/route.ts
  src/app/fonts.ts
  src/app/layout.tsx
  src/assets/fonts/DNFBitBitv2.otf
  src/assets/fonts/DNFBitBitv2.ttf
Labels: 🔨 Refactor

#189 Feat/board notification final
  src/app/(with-main-header)/party/PartyItem.tsx
  src/components/common/Input.tsx
  src/hooks/useSSE.ts
Labels: 🐞 Bug

#192 [FIX] 웹소켓 중복 연결 버그 수정 및 채팅 기능 1개 추가
  src/app/(with-admin-header)/admin/layout.tsx
  src/app/(with-main-header)/chatting/friend/[id]/ChattingList.tsx
  src/app/(with-main-header)/chatting/party/[id]/ChattingList.tsx
  src/app/(with-main-header)/users/[id]/StudyTimeJandyDateChanger.tsx
  src/components/common/WebSocketClient.ts
  src/hooks/useInfiniteChatting.ts
Labels: 🐞 Bug, ✨Feature

#195 Fix/board revalidate bug
  src/api/board/board.ts
  src/app/(with-main-header)/chatting/create/FriendList.tsx
Labels: 🐞 Bug

#198 [FIX] 게시판 revalidate 버그 3차 수정
  src/api/board/board.ts
  src/api/user/user.ts
  src/app/(with-main-header)/boards/[id]/page.tsx
Labels: 🐞 Bug

#199 [FIX] 게시판 revalidate 버그 5차 수정
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
Labels: 🐞 Bug

#202 [FIX] 게시글 revalidate 버그 수정
  src/app/(with-main-header)/boards/PostItem.tsx
  src/app/(with-main-header)/boards/[id]/PostProfile.tsx
Labels: 🐞 Bug

#205 [FIX] 게시글 revalidate 버그 찐찐최종 수정
  src/app/(with-main-header)/boards/[id]/PostProfile.tsx
Labels: 🐞 Bug

#206 메인 파이널 배포
  src/api/user/user.ts
  src/app/(with-main-header)/DesktopHeader.tsx
  src/app/(with-main-header)/MobileHeader.tsx
  src/app/(with-main-header)/boards/create/page.tsx
  src/app/(with-main-header)/mypage/ClosetTab.tsx
  src/app/(with-main-header)/users/[id]/PostsByUser.tsx
Labels: 🐞 Bug, 🔨 Refactor

#209 [HOTFIX]
  src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
Labels: 🐞 Bug
